# Netlify Configuration for PermitIQ Web App
# Deploys the Next.js app from the /web subdirectory

[build]
  # Base directory for the build
  base = "web"
  
  # Build command - use webpack build instead of turbopack for stability
  command = "npm ci && npm run build:webpack"
  
  # Output directory (relative to base)
  publish = ".next"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  
  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Enable caching
  NPM_FLAGS = "--prefer-offline --no-audit"

# Environment variables (set these in Netlify Dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# NEXT_PUBLIC_MAPBOX_TOKEN
# NEXT_PUBLIC_APP_URL

# Redirects and rewrites for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
